
package ies.edxlinbound.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-23T16:35:00.042+03:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "Inbound_EDXL_WebServiceException", targetNamespace = "http://webservice.edxlinbound.ies")
public class InboundEDXLWebServiceException_Exception extends java.lang.Exception {
    
    private ies.edxlinbound.webservice.InboundEDXLWebServiceException inboundEDXLWebServiceException;

    public InboundEDXLWebServiceException_Exception() {
        super();
    }
    
    public InboundEDXLWebServiceException_Exception(String message) {
        super(message);
    }
    
    public InboundEDXLWebServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InboundEDXLWebServiceException_Exception(String message, ies.edxlinbound.webservice.InboundEDXLWebServiceException inboundEDXLWebServiceException) {
        super(message);
        this.inboundEDXLWebServiceException = inboundEDXLWebServiceException;
    }

    public InboundEDXLWebServiceException_Exception(String message, ies.edxlinbound.webservice.InboundEDXLWebServiceException inboundEDXLWebServiceException, Throwable cause) {
        super(message, cause);
        this.inboundEDXLWebServiceException = inboundEDXLWebServiceException;
    }

    public ies.edxlinbound.webservice.InboundEDXLWebServiceException getFaultInfo() {
        return this.inboundEDXLWebServiceException;
    }
}
