package ies.edxlinbound.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-23T16:35:00.080+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "Inbound_EDXL_WebService", 
                  wsdlLocation = "http://lnx1de.iessolutions.eu:3030/axis2/services/Inbound_EDXL_WebService?wsdl",
                  targetNamespace = "http://webservice.edxlinbound.ies") 
public class InboundEDXLWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.edxlinbound.ies", "Inbound_EDXL_WebService");
    public final static QName InboundEDXLWebServiceHttpEndpoint = new QName("http://webservice.edxlinbound.ies", "Inbound_EDXL_WebServiceHttpEndpoint");
    public final static QName InboundEDXLWebServiceHttpSoap11Endpoint = new QName("http://webservice.edxlinbound.ies", "Inbound_EDXL_WebServiceHttpSoap11Endpoint");
    public final static QName InboundEDXLWebServiceHttpSoap12Endpoint = new QName("http://webservice.edxlinbound.ies", "Inbound_EDXL_WebServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://lnx1de.iessolutions.eu:3030/axis2/services/Inbound_EDXL_WebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InboundEDXLWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://lnx1de.iessolutions.eu:3030/axis2/services/Inbound_EDXL_WebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InboundEDXLWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InboundEDXLWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InboundEDXLWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InboundEDXLWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InboundEDXLWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InboundEDXLWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InboundEDXLWebServicePortType
     */
    @WebEndpoint(name = "Inbound_EDXL_WebServiceHttpEndpoint")
    public InboundEDXLWebServicePortType getInboundEDXLWebServiceHttpEndpoint() {
        return super.getPort(InboundEDXLWebServiceHttpEndpoint, InboundEDXLWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InboundEDXLWebServicePortType
     */
    @WebEndpoint(name = "Inbound_EDXL_WebServiceHttpEndpoint")
    public InboundEDXLWebServicePortType getInboundEDXLWebServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(InboundEDXLWebServiceHttpEndpoint, InboundEDXLWebServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns InboundEDXLWebServicePortType
     */
    @WebEndpoint(name = "Inbound_EDXL_WebServiceHttpSoap11Endpoint")
    public InboundEDXLWebServicePortType getInboundEDXLWebServiceHttpSoap11Endpoint() {
        return super.getPort(InboundEDXLWebServiceHttpSoap11Endpoint, InboundEDXLWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InboundEDXLWebServicePortType
     */
    @WebEndpoint(name = "Inbound_EDXL_WebServiceHttpSoap11Endpoint")
    public InboundEDXLWebServicePortType getInboundEDXLWebServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(InboundEDXLWebServiceHttpSoap11Endpoint, InboundEDXLWebServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns InboundEDXLWebServicePortType
     */
    @WebEndpoint(name = "Inbound_EDXL_WebServiceHttpSoap12Endpoint")
    public InboundEDXLWebServicePortType getInboundEDXLWebServiceHttpSoap12Endpoint() {
        return super.getPort(InboundEDXLWebServiceHttpSoap12Endpoint, InboundEDXLWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InboundEDXLWebServicePortType
     */
    @WebEndpoint(name = "Inbound_EDXL_WebServiceHttpSoap12Endpoint")
    public InboundEDXLWebServicePortType getInboundEDXLWebServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(InboundEDXLWebServiceHttpSoap12Endpoint, InboundEDXLWebServicePortType.class, features);
    }

}
