
package com.frequentis.cap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CAP_Inbound", targetNamespace = "http://cap.frequentis.com", wsdlLocation = "http://idira-services.frequentis.com:3001/?wsdl")
public class CAPInbound
    extends Service
{

    private final static URL CAPINBOUND_WSDL_LOCATION;
    private final static WebServiceException CAPINBOUND_EXCEPTION;
    private final static QName CAPINBOUND_QNAME = new QName("http://cap.frequentis.com", "CAP_Inbound");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://idira-services.frequentis.com:3001/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAPINBOUND_WSDL_LOCATION = url;
        CAPINBOUND_EXCEPTION = e;
    }

    public CAPInbound() {
        super(__getWsdlLocation(), CAPINBOUND_QNAME);
    }

    public CAPInbound(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAPINBOUND_QNAME, features);
    }

    public CAPInbound(URL wsdlLocation) {
        super(wsdlLocation, CAPINBOUND_QNAME);
    }

    public CAPInbound(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAPINBOUND_QNAME, features);
    }

    public CAPInbound(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CAPInbound(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICAPInbound
     */
    @WebEndpoint(name = "BasicHttpBinding_ICAP_Inbound")
    public ICAPInbound getBasicHttpBindingICAPInbound() {
        return super.getPort(new QName("http://cap.frequentis.com", "BasicHttpBinding_ICAP_Inbound"), ICAPInbound.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICAPInbound
     */
    @WebEndpoint(name = "BasicHttpBinding_ICAP_Inbound")
    public ICAPInbound getBasicHttpBindingICAPInbound(WebServiceFeature... features) {
        return super.getPort(new QName("http://cap.frequentis.com", "BasicHttpBinding_ICAP_Inbound"), ICAPInbound.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAPINBOUND_EXCEPTION!= null) {
            throw CAPINBOUND_EXCEPTION;
        }
        return CAPINBOUND_WSDL_LOCATION;
    }

}
