
package com.frequentis.cap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICAP_Inbound", targetNamespace = "http://cap.frequentis.com/")
@XmlSeeAlso({
    com.frequentis.cap.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface ICAPInbound {


    /**
     * 
     * @param capMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveCAP", action = "http://cap.frequentis.com/ICAP_Inbound/SaveCAP")
    @WebResult(name = "SaveCAPResult", targetNamespace = "http://cap.frequentis.com/")
    @RequestWrapper(localName = "SaveCAP", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.SaveCAP")
    @ResponseWrapper(localName = "SaveCAPResponse", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.SaveCAPResponse")
    public String saveCAP(
        @WebParam(name = "CapMessage", targetNamespace = "http://cap.frequentis.com/")
        String capMessage);

    /**
     * 
     * @param area
     * @param includeOlderMsgs
     * @param receiver
     * @param password
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "ReadCAP", action = "http://cap.frequentis.com/ICAP_Inbound/ReadCAP")
    @WebResult(name = "ReadCAPResult", targetNamespace = "http://cap.frequentis.com/")
    @RequestWrapper(localName = "ReadCAP", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.ReadCAP")
    @ResponseWrapper(localName = "ReadCAPResponse", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.ReadCAPResponse")
    public ArrayOfstring readCAP(
        @WebParam(name = "Receiver", targetNamespace = "http://cap.frequentis.com/")
        String receiver,
        @WebParam(name = "Password", targetNamespace = "http://cap.frequentis.com/")
        String password,
        @WebParam(name = "Area", targetNamespace = "http://cap.frequentis.com/")
        String area,
        @WebParam(name = "IncludeOlderMsgs", targetNamespace = "http://cap.frequentis.com/")
        Boolean includeOlderMsgs);

    /**
     * 
     * @param capMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateCAP", action = "http://cap.frequentis.com/ICAP_Inbound/ValidateCAP")
    @WebResult(name = "ValidateCAPResult", targetNamespace = "http://cap.frequentis.com/")
    @RequestWrapper(localName = "ValidateCAP", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.ValidateCAP")
    @ResponseWrapper(localName = "ValidateCAPResponse", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.ValidateCAPResponse")
    public String validateCAP(
        @WebParam(name = "CapMessage", targetNamespace = "http://cap.frequentis.com/")
        String capMessage);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SupportedCAPVersion", action = "http://cap.frequentis.com/ICAP_Inbound/SupportedCAPVersion")
    @WebResult(name = "SupportedCAPVersionResult", targetNamespace = "http://cap.frequentis.com/")
    @RequestWrapper(localName = "SupportedCAPVersion", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.SupportedCAPVersion")
    @ResponseWrapper(localName = "SupportedCAPVersionResponse", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.SupportedCAPVersionResponse")
    public String supportedCAPVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SupportedCAPSchema", action = "http://cap.frequentis.com/ICAP_Inbound/SupportedCAPSchema")
    @WebResult(name = "SupportedCAPSchemaResult", targetNamespace = "http://cap.frequentis.com/")
    @RequestWrapper(localName = "SupportedCAPSchema", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.SupportedCAPSchema")
    @ResponseWrapper(localName = "SupportedCAPSchemaResponse", targetNamespace = "http://cap.frequentis.com/", className = "com.frequentis.cap.SupportedCAPSchemaResponse")
    public String supportedCAPSchema();

}
